# This is a basic workflow to help you get started with Actions

name: CI
#env:
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          #owner: 'GuillaumeFalourd'
          #repository: 'poc-github-actions'
          owner: 'AkeemSemper'
          #repository: 'Programming_for_ML_Student_Workbooks'
          repository: 'ML_for_Non_DS_Students'
          #repository: 'ml_data'
          submodule: True
          #depth: 5
          #access-token: ${{ secrets.ACCESS_TOKEN }}
          access-token: ${{ Setup.ACCESS_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          # Workbooks
          rm -rf workbooks
          mkdir workbooks
          cp -r ML_for_Non_DS_Students/class_workbooks/*.ipynb workbooks
          ls -la workbooks

          # Images
          rm -rf images
          mkdir images
          cp -r ML_for_Non_DS_Students/images/* images

          # Data

          # Resources
          rm -rf course_resources
          mkdir course_resources
          cp -r ML_for_Non_DS_Students/course_resources/* course_resources

          ## Supplementary Practice Workbooks
          rm -rf ssupplementary_practice_workbooks
          mkdir supplementary_practice_workbooks
          cp -r ML_for_Non_DS_Students/supplementary_practice_workbooks/*.ipynb supplementary_practice_workbooks

          # Clear
          rm -rf ML_for_Non_DS_Students

      # Commit all changed files back to the repository
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: '--no-verify --signoff'
