# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Copy Environment Variables
        run: |
          echo "GH_PAT=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
      
      - name: Open Original Repository
        uses: actions/checkout@v4
        with:
          repository: 'AkeemSemper/Programming_for_ML_Student_Workbooks'
          ref: 'main'

          #token: ${{ secrets.GH_PAT }}
      - name: Check Rep
        run: |
          ls
          git status

      #- name: Setup commit files
      #  uses: actions/checkout@v4
      #  with:
      #    repository: 'AkeemSemper/ML_for_Non_DS_Students'
      #    ref: 'main'
      #    #token: ${{ secrets.GITHUB_TOKEN }}
      #    #token: ${{ secrets.COPY_PAT }}
      #    token: ${{ secrets.GH_PAT }}
      #    path: 'ML_for_Non_DS_Students'

      - name: Clone GuillaumeFalourd/poc-github-actions PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'AkeemSemper'
          repository: 'ML_for_Non_DS_Students'
          access-token: ${{ secrets.GH_PAT }}

      - name: Access cloned repository content
        run: |
          # Check Status
          #ls -rf

          # Workbooks
          rm -rf workbooks
          mkdir workbooks
          cp -r ML_for_Non_DS_Students/class_workbooks/*.ipynb workbooks
          #ls -la workbooks

          # Images
          rm -rf images
          mkdir images
          cp -r ML_for_Non_DS_Students/images/* images

          # Data

          # Resources
          rm -rf course_resources
          mkdir course_resources
          cp -r ML_for_Non_DS_Students/course_resources/* course_resources

          ## Supplementary Practice Workbooks
          rm -rf supplementary_practice_workbooks
          mkdir supplementary_practice_workbooks
          cp -r ML_for_Non_DS_Students/supplementary_practice_workbooks/*.ipynb supplementary_practice_workbooks

          # Clear
          rm -rf ML_for_Non_DS_Students
          #cd
          #ls
          
          #ls
          #cd ../
          #git status
          #git init
          #git add .
          #git remote add origin https://github.com/AkeemSemper/Programming_for_ML_Student_Workbooks.git
          #git push origin main
          #git push --set-upstream https://github.com/AkeemSemper/Programming_for_ML_Student_Workbooks.git origin

          #git init
          #git config --global init.defaultBranch main
          #git config user.name "Akeem Semper"
          #git config user.email "akeem.semper@gmail.com"
          #git add .
          #git commit -m "Prep for Commit"

          #git push --force
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generated Update from Main Repository"
          git push --force
      # Commit all changed files back to the repository
      #- name: Commit files
        #uses: stefanzweifel/git-auto-commit-action@v5
        #with:
          #repository: 'AkeemSemper/Programming_for_ML_Student_Workbooks'
          #owner: 'AkeemSemper'
          #repository: 'Programming_for_ML_Student_Workbooks'
          #commit_options: '--no-verify --signoff'
          #branch: main
          #token: ${{ secrets.GH_PAT }}
          #commit_message: "Update files from Base Repository"
          #skip_dirty_check: true